# Generated by Django 5.2.12 on 2026-03-29 00:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canbet_app', '0002_space_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lootbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('crate_type', models.CharField(choices=[('SPOOKY', 'Spooky Crate'), ('SPACE', 'Space Crate'), ('FANTASY', 'Fantasy Crate'), ('WEATHER', 'Weather Crate')], max_length=16)),
                ('cost_bits', models.IntegerField(default=100)),
                ('sprite_path', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LootboxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canbet_app.item')),
                ('loot_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='canbet_app.lootbox')),
            ],
            options={
                'unique_together': {('loot_box', 'item')},
            },
        ),
        migrations.CreateModel(
            name='LootboxInventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('obtained_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loot_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canbet_app.lootbox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loot_box_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'loot_box')},
            },
        ),
    ]
